import type {
  Property,
  Tenant,
  Payment,
  MaintenanceTicket,
  DashboardStats,
  Notification,
  User,
  Unit,
} from "@/types";

export const mockUser: User = {
  id: "usr_001",
  email: "admin@propmanage.com",
  name: "Alex Morgan",
  role: "ADMIN",
  phone: "(555) 123-4567",
  avatarUrl: undefined,
  createdAt: new Date("2024-01-15"),
  updatedAt: new Date("2024-06-01"),
};

export const mockProperties: Property[] = [
  {
    id: "prop_001",
    name: "Riverside Apartments",
    address: "142 River Rd",
    city: "Youngstown",
    state: "OH",
    zipCode: "44503",
    type: "APARTMENT",
    status: "ACTIVE",
    units: 24,
    occupiedUnits: 21,
    monthlyRevenue: 28350,
    imageUrl: "/images/property-1.jpg",
    description: "Modern apartment complex with river views",
    amenities: ["Pool", "Gym", "Parking", "Laundry"],
    managerId: "usr_001",
    createdAt: new Date("2023-06-15"),
    updatedAt: new Date("2024-05-01"),
  },
  {
    id: "prop_002",
    name: "Oakwood Townhomes",
    address: "890 Oak St",
    city: "Boardman",
    state: "OH",
    zipCode: "44512",
    type: "TOWNHOUSE",
    status: "ACTIVE",
    units: 12,
    occupiedUnits: 10,
    monthlyRevenue: 18000,
    imageUrl: "/images/property-2.jpg",
    description: "Family-friendly townhome community",
    amenities: ["Garage", "Backyard", "Playground", "Pet Friendly"],
    managerId: "usr_001",
    createdAt: new Date("2023-09-01"),
    updatedAt: new Date("2024-04-15"),
  },
  {
    id: "prop_003",
    name: "Downtown Lofts",
    address: "55 Federal St",
    city: "Youngstown",
    state: "OH",
    zipCode: "44503",
    type: "CONDO",
    status: "ACTIVE",
    units: 18,
    occupiedUnits: 16,
    monthlyRevenue: 25600,
    imageUrl: "/images/property-3.jpg",
    description: "Converted industrial lofts in downtown",
    amenities: ["Rooftop", "Concierge", "Bike Storage", "EV Charging"],
    managerId: "usr_001",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-05-20"),
  },
  {
    id: "prop_004",
    name: "Maple Heights",
    address: "321 Maple Ave",
    city: "Canfield",
    state: "OH",
    zipCode: "44406",
    type: "HOUSE",
    status: "ACTIVE",
    units: 6,
    occupiedUnits: 6,
    monthlyRevenue: 10800,
    imageUrl: "/images/property-4.jpg",
    description: "Single-family rental homes",
    amenities: ["Garage", "Backyard", "Central Air", "Washer/Dryer"],
    managerId: "usr_001",
    createdAt: new Date("2023-03-20"),
    updatedAt: new Date("2024-06-01"),
  },
];

export const mockUnits: Unit[] = [
  { id: "unit_001", propertyId: "prop_001", unitNumber: "101", floor: 1, bedrooms: 1, bathrooms: 1, sqft: 650, rent: 1050, status: "OCCUPIED", tenantId: "ten_001" },
  { id: "unit_002", propertyId: "prop_001", unitNumber: "102", floor: 1, bedrooms: 2, bathrooms: 1, sqft: 900, rent: 1350, status: "OCCUPIED", tenantId: "ten_002" },
  { id: "unit_003", propertyId: "prop_001", unitNumber: "103", floor: 1, bedrooms: 1, bathrooms: 1, sqft: 650, rent: 1050, status: "VACANT" },
  { id: "unit_004", propertyId: "prop_001", unitNumber: "201", floor: 2, bedrooms: 2, bathrooms: 2, sqft: 1100, rent: 1500, status: "OCCUPIED", tenantId: "ten_003" },
  { id: "unit_005", propertyId: "prop_001", unitNumber: "202", floor: 2, bedrooms: 3, bathrooms: 2, sqft: 1400, rent: 1800, status: "MAINTENANCE" },
];

export const mockTenants: Tenant[] = [
  {
    id: "ten_001",
    userId: "usr_010",
    user: { id: "usr_010", email: "sarah.j@email.com", name: "Sarah Johnson", role: "TENANT", createdAt: new Date(), updatedAt: new Date() },
    unitId: "unit_001",
    propertyId: "prop_001",
    leaseStart: new Date("2024-01-01"),
    leaseEnd: new Date("2025-01-01"),
    leaseStatus: "ACTIVE",
    monthlyRent: 1050,
    securityDeposit: 1050,
    moveInDate: new Date("2024-01-01"),
  },
  {
    id: "ten_002",
    userId: "usr_011",
    user: { id: "usr_011", email: "mike.c@email.com", name: "Mike Chen", role: "TENANT", createdAt: new Date(), updatedAt: new Date() },
    unitId: "unit_002",
    propertyId: "prop_001",
    leaseStart: new Date("2024-03-01"),
    leaseEnd: new Date("2025-03-01"),
    leaseStatus: "ACTIVE",
    monthlyRent: 1350,
    securityDeposit: 1350,
    moveInDate: new Date("2024-03-01"),
  },
  {
    id: "ten_003",
    userId: "usr_012",
    user: { id: "usr_012", email: "lisa.w@email.com", name: "Lisa Wang", role: "TENANT", createdAt: new Date(), updatedAt: new Date() },
    unitId: "unit_004",
    propertyId: "prop_001",
    leaseStart: new Date("2023-09-01"),
    leaseEnd: new Date("2024-09-01"),
    leaseStatus: "ACTIVE",
    monthlyRent: 1500,
    securityDeposit: 1500,
    moveInDate: new Date("2023-09-01"),
  },
  {
    id: "ten_004",
    userId: "usr_013",
    user: { id: "usr_013", email: "raj.p@email.com", name: "Raj Patel", role: "TENANT", createdAt: new Date(), updatedAt: new Date() },
    unitId: "unit_010",
    propertyId: "prop_002",
    leaseStart: new Date("2024-06-01"),
    leaseEnd: new Date("2025-06-01"),
    leaseStatus: "ACTIVE",
    monthlyRent: 1800,
    securityDeposit: 1800,
    moveInDate: new Date("2024-06-01"),
  },
];

export const mockPayments: Payment[] = [
  {
    id: "pay_001", tenantId: "ten_001", propertyId: "prop_001", unitId: "unit_001",
    amount: 1050, status: "COMPLETED", method: "CARD", description: "Rent - January 2025",
    dueDate: new Date("2025-01-01"), paidDate: new Date("2024-12-28"),
    stripePaymentId: "pi_abc123", createdAt: new Date("2024-12-28"),
  },
  {
    id: "pay_002", tenantId: "ten_002", propertyId: "prop_001", unitId: "unit_002",
    amount: 1350, status: "COMPLETED", method: "BANK_TRANSFER", description: "Rent - January 2025",
    dueDate: new Date("2025-01-01"), paidDate: new Date("2024-12-30"),
    createdAt: new Date("2024-12-30"),
  },
  {
    id: "pay_003", tenantId: "ten_003", propertyId: "prop_001", unitId: "unit_004",
    amount: 1500, status: "PENDING", method: "CARD", description: "Rent - February 2025",
    dueDate: new Date("2025-02-01"), createdAt: new Date("2025-01-25"),
  },
  {
    id: "pay_004", tenantId: "ten_004", propertyId: "prop_002", unitId: "unit_010",
    amount: 1800, status: "FAILED", method: "CARD", description: "Rent - January 2025",
    dueDate: new Date("2025-01-01"), createdAt: new Date("2025-01-01"),
  },
  {
    id: "pay_005", tenantId: "ten_001", propertyId: "prop_001", unitId: "unit_001",
    amount: 1050, status: "PENDING", method: "CARD", description: "Rent - February 2025",
    dueDate: new Date("2025-02-01"), createdAt: new Date("2025-01-28"),
  },
];

export const mockTickets: MaintenanceTicket[] = [
  {
    id: "tkt_001", tenantId: "ten_001", propertyId: "prop_001", unitId: "unit_001",
    title: "Leaking kitchen faucet", description: "The kitchen faucet has been dripping constantly for the past 3 days. Water is pooling under the sink.",
    category: "PLUMBING", priority: "HIGH", status: "IN_PROGRESS",
    assignedTo: "Bob's Plumbing", images: [], notes: [
      { id: "n1", ticketId: "tkt_001", authorId: "usr_001", authorName: "Alex Morgan", content: "Scheduled plumber for Tuesday morning.", createdAt: new Date("2025-01-20") },
    ],
    estimatedCost: 150, scheduledDate: new Date("2025-01-28"),
    createdAt: new Date("2025-01-18"), updatedAt: new Date("2025-01-20"),
  },
  {
    id: "tkt_002", tenantId: "ten_002", propertyId: "prop_001", unitId: "unit_002",
    title: "Thermostat not working", description: "The thermostat display is blank and heat won't turn on.",
    category: "HVAC", priority: "URGENT", status: "OPEN",
    images: [], notes: [],
    createdAt: new Date("2025-01-22"), updatedAt: new Date("2025-01-22"),
  },
  {
    id: "tkt_003", tenantId: "ten_003", propertyId: "prop_001", unitId: "unit_004",
    title: "Broken window latch", description: "The bedroom window latch is broken. Window won't lock properly.",
    category: "STRUCTURAL", priority: "MEDIUM", status: "WAITING",
    assignedTo: "HandyPro Services", images: [], notes: [],
    estimatedCost: 75, scheduledDate: new Date("2025-02-02"),
    createdAt: new Date("2025-01-15"), updatedAt: new Date("2025-01-17"),
  },
  {
    id: "tkt_004", tenantId: "ten_004", propertyId: "prop_002", unitId: "unit_010",
    title: "Dishwasher making loud noise", description: "Dishwasher started making grinding noises during the wash cycle.",
    category: "APPLIANCE", priority: "LOW", status: "RESOLVED",
    assignedTo: "A+ Appliance Repair", images: [], notes: [],
    estimatedCost: 200, actualCost: 175, resolvedDate: new Date("2025-01-21"),
    createdAt: new Date("2025-01-10"), updatedAt: new Date("2025-01-21"),
  },
];

export const mockNotifications: Notification[] = [
  { id: "notif_001", userId: "usr_001", type: "PAYMENT_RECEIVED", title: "Payment Received", message: "Sarah Johnson paid $1,050 for January rent", read: false, actionUrl: "/payments/pay_001", createdAt: new Date("2024-12-28") },
  { id: "notif_002", userId: "usr_001", type: "MAINTENANCE_UPDATE", title: "New Maintenance Request", message: "Urgent: Thermostat not working in Unit 102", read: false, actionUrl: "/maintenance/tkt_002", createdAt: new Date("2025-01-22") },
  { id: "notif_003", userId: "usr_001", type: "PAYMENT_LATE", title: "Late Payment Alert", message: "Raj Patel's payment for January is 22 days overdue", read: true, actionUrl: "/payments/pay_004", createdAt: new Date("2025-01-23") },
  { id: "notif_004", userId: "usr_001", type: "LEASE_EXPIRING", title: "Lease Expiring Soon", message: "Lisa Wang's lease expires in 30 days", read: true, actionUrl: "/tenants/ten_003", createdAt: new Date("2025-01-20") },
];

export const mockDashboardStats: DashboardStats = {
  totalProperties: 4,
  totalUnits: 60,
  occupancyRate: 88,
  totalRevenue: 82750,
  pendingPayments: 8,
  openTickets: 3,
  expiringLeases: 2,
  recentPayments: mockPayments.slice(0, 4),
  recentTickets: mockTickets.slice(0, 3),
  revenueByMonth: [
    { month: "Aug", revenue: 76200, expenses: 12400 },
    { month: "Sep", revenue: 78800, expenses: 15200 },
    { month: "Oct", revenue: 79100, expenses: 11800 },
    { month: "Nov", revenue: 80500, expenses: 14600 },
    { month: "Dec", revenue: 81200, expenses: 18900 },
    { month: "Jan", revenue: 82750, expenses: 13200 },
  ],
  occupancyByProperty: [
    { property: "Riverside Apartments", rate: 87.5 },
    { property: "Oakwood Townhomes", rate: 83.3 },
    { property: "Downtown Lofts", rate: 88.9 },
    { property: "Maple Heights", rate: 100 },
  ],
};
